### ISSUE TITLE
Bass / Treble / EQ setting

### ISSUE THREAD

**Issue by deluxestyle** [johanfrick/custom-sonos-card#181]
**Is your feature request related to a problem? Please describe.**
not a problem, just a feature request

**Describe the solution you'd like**
It would be great to have the possiblity to set the equalizer of each speaker. the sonos integration is supporting it. Bass and Treble

**Describe alternatives you've considered**
I have added the sliders to my card, but if it would be included in the sonos card it would be great

**Comment by johanfrick** [comment]
Fixed in https://github.com/johanfrick/custom-sonos-card/releases/tag/v6.11.0.

Example 1 for TV:
![image](https://github.com/johanfrick/custom-sonos-card/assets/26582898/040c7231-715b-4a25-865a-1538114dda18)

Example 2 for group with standard players:
![image](https://github.com/johanfrick/custom-sonos-card/assets/26582898/e754b964-4a29-440b-b344-4095a03cefd1)

**Comment by deluxestyle** [comment]
thank you. looks great. 
how to enable it? I downloaded the latest version but don't get the settings

**Comment by johanfrick** [comment]
Did you go to the volumes section? And click the cog?
<img width="262" alt="image" src="https://github.com/johanfrick/custom-sonos-card/assets/26582898/6c22ba5b-eaa6-435b-917c-4a8a7f59220f">

**Comment by deluxestyle** [comment]
yes, and if I click on it I get only the old settings

![grafik](https://github.com/johanfrick/custom-sonos-card/assets/662779/375e5927-3689-4667-b359-99fb0e0178f6)

**Comment by johanfrick** [comment]
That's the old version

**Comment by deluxestyle** [comment]
Seems it was in the cache
I‘ve deleted the card and installed it again. Now it is working. Thank you

**Comment by johanfrick** [comment]
🎉
