### ISSUE TITLE
v6.14.9 Media card blank ??

### ISSUE THREAD

**Issue by pressurejets** [johanfrick/custom-sonos-card#264]
Just updated to v6.14.9 and card on view bank. I have tried reset and add new cards didnt help ??

**Comment by johanfrick** [comment]
There is a bug template. Please use it

**Comment by phateks** [comment]
can u point me in the direction of the bug template pls?? same issue here, 14.9, 15.0 no card
Thank You

**Comment by johanfrick** [comment]
Just click new issue in github, then click on bug report, then use the template in the description

**Comment by phateks** [comment]
just a quick question, the card has a dependency of owning a sonos device?
i have the same problem as ia had it few weeks ago, just disappeared for no reason, and before that was able to work with an Arylic device, dlna/ Airplay, Samsung TV's and Nest Mini.
Tried 14.9, 15.0, 15.0 beta 2, same story.
Or it has any dependency of any other integration ?
I'm getting really frustrated and it's the only thing that i like using for media playback because of ease of media devices access and access to favorites.
Sorry if i'm buggin' u.
Thanks !!

**Comment by johanfrick** [comment]
Fair point, I had no idea it worked so well with other platforms 🎉 I only have Sonos myself.
I disabled it because of this bug: https://github.com/johanfrick/custom-sonos-card/issues/257
I'll revert part of it to make it possible to use other platforms.

**Comment by phateks** [comment]
it's the only thing that come's in mind. 
i installed airsonos add-on, and at one point through sonos card i could pai 2 TV's and broadcast music on them
after an update could not see one of the tv-s, and looking back i thought maybe it has some dependencies on types of media players

**Comment by johanfrick** [comment]
Please try this one: https://github.com/johanfrick/custom-sonos-card/releases/tag/v6.15.1

**Comment by phateks** [comment]
![image](https://github.com/johanfrick/custom-sonos-card/assets/134103405/6a2bd232-e16d-4bd1-88c4-fc5c5dec062d)
showed up again
can't see tv's but i have to get home and test if all ok

**Comment by johanfrick** [comment]
Which version does it work with favorites?

**Comment by johanfrick** [comment]
music assistant?

**Comment by phateks** [comment]
addon from HAOS, but does not have a card for it
![image](https://github.com/johanfrick/custom-sonos-card/assets/134103405/c217f595-10f7-4c41-adf2-16804bce1895)

**Comment by phateks** [comment]
as a backup i installed music assistant, and put some radio stations and playlist in a favorites tab on there, and when i looked into sonos card, they were just there, after your updates, the were gone, and tried to put them in config as documentation said, but nothing shows up, and i saw that was in issue a while back with favorites but they were accessed from a sonos device, thats why i'm thinking also a dependency on that

**Comment by johanfrick** [comment]
I'd like to see how your players look:
1. go to http://homeassistant.local:8123/developer-tools/template
2. paste `{{states['media_player.kok'].attributes}}`
    1. replace with your own media player ids
    2. do this for every player you have
3. share the output here

**Comment by phateks** [comment]
![image](https://github.com/johanfrick/custom-sonos-card/assets/134103405/ace6492e-1538-4edf-9d1f-66efe7fc5343)
![image](https://github.com/johanfrick/custom-sonos-card/assets/134103405/2ac1348f-1377-4d5d-b7bf-8ff12c1cd185)
![image](https://github.com/johanfrick/custom-sonos-card/assets/134103405/a39e2fa8-5cff-4f04-a398-7938552af044)
![image](https://github.com/johanfrick/custom-sonos-card/assets/134103405/5492af70-3fff-4f4a-806e-7f783eca5969)

**Comment by johanfrick** [comment]
Nothing that indicates anything about favorites there. Please install the old version of the card again to make sure you see favorites with that version.

**Comment by phateks** [comment]
installed 13.1 and actually i realized that because when i was browsing media stayed at last location, so actually i was always in the same folder from where i was playing music. Now because the favorites and browser are separated that illusion of favorites is gone :) . i'll install the 15.1 release and maybe i'll figure why favorites are not showing
thank you!!!!
