### ISSUE TITLE
Login attempt failed

### ISSUE THREAD

**Issue by fortunatomarzagalli** [johanfrick/custom-sonos-card#90]
First of all, let me say that I really like this Custom Sonos Card. 

I see an unexpected result from the use of this card, that anyway does not block the use of the card. 
In my setup I have a dummy user called "home", used in the tablet next to the main entrance (the tablet address is 192.168.50.50). 

When I load the Sonos Card in my Lovelace interface I receive a notification EVERY SECOND that says

"Login attempt or request with invalid authentication from 192.168.50.50 (192.168.50.50). See the log for details."

And in the logs:

Logger: homeassistant.components.http.ban
Source: components/http/ban.py:84
Integration: HTTP (documentation, issues)
First occurred: 16:16:17 (749 occurrences)
Last logged: 16:28:31

Login attempt or request with invalid authentication from 192.168.50.50 (192.168.50.50). Requested URL: '/api/template'. (Mozilla/5.0 (Linux; Android 9; KFTRWI Build/PS7324.3016N; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/102.0.5005.125 Safari/537.36)

As you see... 12 minutes, 749 notifications :))

I also use the same card from other devices with my main account, and this does not generates any notification
However the Sonos Card works fine from the tablet ... 

can you help me?

thanks

Fortunato

**Comment by johanfrick** [comment]
Thanks for reporting this. Not sure how to address it at the moment, but will keep the issue open hoping for someone to provide some ideas on how to solve it.

**Comment by dperkerson** [comment]
I'm having this issue as well. Only a non_admin user generates the error and there appears be no impact on the functionality. I'll help with testing if there is something that you would like me to try.

**Comment by dperkerson** [comment]
I did a packet trace on this tonight. It only happens when a non-admin user loads the page. Everytime it tries to open api/template it gets a 401 Unauthorized. I attached the packet capture in case it helps with diagnosis.
[sonos tab filtered.zip](https://github.com/johanfrick/custom-sonos-card/files/10291359/sonos.tab.filtered.zip)

**Comment by johanfrick** [comment]
Thanks, any suggestions how to fix it?

**Comment by nikokyritsis** [comment]
This appears to be related to the getRelatedSwitchEntities function, which is using callApi to render a template for additional player switches. I'm guessing it works for Admin users because they're authorized to access the API but non-Admin users are not passing an Authorization header that allows them to complete the call successfully. This function is only used to render additional buttons on the player, so you can work around the error by setting skipAdditionalPlayerSwitches to true in your card configuration if you don't need the additional buttons.

I'm not too familiar with Home Assistant cards yet so I don't have a suggested solution but I will dig a little further and see what I can offer to help.

**Comment by nkyritsis** [comment]
This appears to be related to the getRelatedSwitchEntities function, which is using callApi to render a template for additional player switches. I'm guessing it works for Admin users because they're authorized to access the API but non-Admin users are not passing an Authorization header that allows them to complete the call successfully. This function is only used to render additional buttons on the player, so you can work around the error by setting skipAdditionalPlayerSwitches to true in your card configuration if you don't need the additional buttons.

I'm not too familiar with Home Assistant cards yet so I don't have a suggested solution but I will dig a little further and see what I can offer to help.

**Comment by dperkerson** [comment]
Most excellent!

I added "skipAdditionalPlayerSwitches: true" to my yaml file for this dashboard and the error no longer occurs. I cannot find any feature that has stopped working so I'm guessing I don't use what it is offering.

Thanks for jumping in and helping us!

**Comment by johanfrick** [comment]
Thanks a lot everyone who dug into this!
Looks like I was using an API endpoint that requires admin. I changed to fetching the information over websockets, and now it works for non-admins as well. So you do not have to have this config anymore: `skipAdditionalPlayerSwitches: true`.
@dperkerson @nkyritsis @fortunatomarzagalli , please try this version: [v5.19.1](https://github.com/johanfrick/custom-sonos-card/releases/tag/v5.19.1)
